CREATE TABLE Sources (
	id BIGINT GENERATED BY DEFAULT AS IDENTITY,
	contentType varchar(255) not null,
	url varchar(255) not null
);

insert into Sources (contentType, url) values ('HTML', 'http://www.trustartist.com');
